packages:
  - lib/cli
  - lib/core
  - lib/python-sdk
  - lib/changelog-emitter
  - lib/ts-sdk
  - website

overrides:
  diff@<8.0.3: '>=8.0.3'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  qs@<6.14.1: '>=6.14.1'
  tar@=7.5.1: '>=7.5.2'
  undici@>=7.0.0 <7.18.2: '>=7.18.2'
