packages:
  - lib/cli
  - lib/core
  - lib/python-sdk
  - lib/changelog-emitter
  - lib/ts-sdk
  - website

overrides:
  "@isaacs/brace-expansion@<=5.0.0": ">=5.0.1"
  axios@<=1.13.4: ">=1.13.5"
  devalue@<=5.6.2: ">=5.6.3"
  diff@<8.0.3: ">=8.0.3"
  fast-xml-parser@>=4.1.3 <5.3.6: ">=5.3.6"
  glob@>=10.2.0 <10.5.0: ">=10.5.0"
  lodash@>=4.0.0 <=4.17.22: ">=4.17.23"
  minimatch@<10.2.1: ">=10.2.1"
  qs@<6.14.1: ">=6.14.2"
  tar@<7.5.8: ">=7.5.8"
  rollup@>=4.0.0 <4.59.0: ">=4.59.0"
  undici@>=7.0.0 <7.18.2: ">=7.18.2"

auditConfig:
  ignoreGhsas:
    - GHSA-2g4f-4pwh-qvx6

catalog:
  "@types/node": ^20.19.23
  "@typespec/compiler": ^1.9.0
  "@typespec/http": ^1.9.0
  "@typespec/json-schema": ^1.9.0
  "@typespec/openapi": ^1.9.0
  "@typespec/openapi3": ^1.9.0
  "@typespec/rest": ^0.79.0
  "@typespec/versioning": ^0.79.0
  "@vitest/coverage-v8": ^3.2.4
  eslint-plugin-vitest: ^0.5.4
  vitest: ^3.2.4

catalogs:
  website:
    vitest: ^4.0.17
