"""
Pydantic schemas for the CommonGrants API.

These schemas are based on the TypeSpec models defined in the CommonGrants specification.
"""

# Import and re-export all models from the Python SDK
from common_grants_sdk.schemas.pydantic import (
    ArrayOperator,
    ComparisonOperator,
    # Fields
    CustomField,
    CustomFieldType,
    DateComparisonFilter,
    DateRange,
    DateRangeFilter,
    # Types
    DecimalString,
    # Filters
    DefaultFilter,
    # Responses
    DefaultResponse,
    EquivalenceOperator,
    Error,
    Event,
    Filtered,
    FilterInfo,
    InvalidMoneyValueError,
    ISODate,
    ISOTime,
    Money,
    MoneyComparisonFilter,
    MoneyRange,
    MoneyRangeFilter,
    OppDefaultFilters,
    OppFilters,
    OppFunding,
    OpportunitiesListResponse,
    OpportunitiesSearchResponse,
    # Models
    OpportunityBase,
    OpportunityResponse,
    # Requests
    OpportunitySearchRequest,
    # Sorting
    OppSortBy,
    OppSorting,
    OppStatus,
    OppStatusOptions,
    OppTimeline,
    Paginated,
    # Paginated
    PaginatedBase,
    PaginatedBodyParams,
    PaginatedResultsInfo,
    RangeOperator,
    Sorted,
    SortedResultsInfo,
    StringArrayFilter,
    StringComparisonFilter,
    StringOperator,
    Success,
    SystemMetadata,
    UTCDateTime,
)

__all__ = [
    "ArrayOperator",
    "ComparisonOperator",
    "CustomField",
    "CustomFieldType",
    "DateComparisonFilter",
    "DateRange",
    "DateRangeFilter",
    "DecimalString",
    "DefaultFilter",
    "DefaultResponse",
    "EquivalenceOperator",
    "Error",
    "Event",
    "FilterInfo",
    "Filtered",
    "ISODate",
    "ISOTime",
    "InvalidMoneyValueError",
    "Money",
    "MoneyComparisonFilter",
    "MoneyRange",
    "MoneyRangeFilter",
    "OppDefaultFilters",
    "OppFilters",
    "OppFunding",
    "OppSortBy",
    "OppSorting",
    "OppStatus",
    "OppStatusOptions",
    "OppTimeline",
    "OpportunitiesListResponse",
    "OpportunitiesSearchResponse",
    "OpportunityBase",
    "OpportunityResponse",
    "OpportunitySearchRequest",
    "Paginated",
    "PaginatedBase",
    "PaginatedBodyParams",
    "PaginatedResultsInfo",
    "RangeOperator",
    "Sorted",
    "SortedResultsInfo",
    "StringArrayFilter",
    "StringComparisonFilter",
    "StringOperator",
    "Success",
    "SystemMetadata",
    "UTCDateTime",
]
