$schema: https://json-schema.org/draft/2020-12/schema
$id: ApplicationBase.yaml
type: object
properties:
  id:
    $ref: uuid.yaml
    description: The unique identifier for the application
  name:
    type: string
    description: The name of the application
  competitionId:
    $ref: uuid.yaml
    description: The unique identifier for the competition
  formResponses:
    $ref: "#/$defs/RecordAppFormResponse"
    description: The form responses for the application
  status:
    $ref: AppStatus.yaml
    description: The status of the application
  submittedAt:
    anyOf:
      - type: string
        format: date-time
      - type: "null"
    description: The date and time the application was submitted
  customFields:
    $ref: "#/$defs/RecordCustomField"
    description: The custom fields about the application
  createdAt:
    type: string
    format: date-time
    description: The timestamp (in UTC) at which the record was created.
  lastModifiedAt:
    type: string
    format: date-time
    description: The timestamp (in UTC) at which the record was last modified.
required:
  - id
  - name
  - competitionId
  - formResponses
  - status
  - createdAt
  - lastModifiedAt
$defs:
  RecordAppFormResponse:
    type: object
    properties: {}
    unevaluatedProperties:
      $ref: AppFormResponse.yaml
  RecordCustomField:
    type: object
    properties: {}
    unevaluatedProperties:
      $ref: CustomField.yaml
