$schema: https://json-schema.org/draft/2020-12/schema
$id: ApplicationBase.yaml
type: object
properties:
  id:
    $ref: uuid.yaml
    description: The application's unique identifier.
  status:
    $ref: AppStatus.yaml
    description: The application's status.
  dateSubmitted:
    $ref: isoDate.yaml
    description: The application's date of submission.
  organization:
    $ref: OrganizationBase.yaml
    description: The organization that is applying for the grant.
  pointOfContact:
    $ref: PersonBase.yaml
    description: The person who is applying for the grant.
  proposal:
    $ref: AppProposal.yaml
    description: The application's proposal for funding.
  opportunity:
    $ref: AppOpportunity.yaml
    description: The opportunity being applied to.
  customFields:
    $ref: "#/$defs/RecordCustomField"
    description: The application's custom fields.
required:
  - id
examples:
  - id: 083b4567-e89d-42c8-a439-6c1234567890
    status:
      value: submitted
      description: Application has been submitted.
    dateSubmitted: 2024-01-01
    organization:
      id: 083b4567-e89d-42c8-a439-6c1234567890
      name: Example Organization
      type:
        term: Hospital
        class: Organization types
        description: Institutions with the primary purpose of providing in-patient physical and mental health services...
        code: EO000000
      ein: 12-3456789
      uei: ABC1234567890
      duns: "123456789012"
      addresses:
        primary:
          street1: 456 Main St
          street2: Suite 100
          city: Anytown
          stateOrProvince: CA
          country: US
          postalCode: "12345"
        otherAddresses:
          satellite:
            street1: 456 Main St
            street2: Suite 100
            city: Anytown
            stateOrProvince: CA
            country: US
            postalCode: "12345"
          international:
            street1: 123 Rue Principale
            city: Montreal
            stateOrProvince: QC
            country: CA
            postalCode: H2Y 1C6
      phones:
        primary:
          countryCode: "+1"
          number: 444-456-1230
          isMobile: true
        fax:
          countryCode: "+1"
          number: 555-123-4567
          extension: "123"
          isMobile: false
        otherPhones:
          support:
            countryCode: "+1"
            number: 333-456-1230
            isMobile: false
          marketing:
            countryCode: "+1"
            number: 444-456-1230
            isMobile: true
      emails:
        primary: info@example.com
        otherEmails:
          support: support@example.com
          marketing: marketing@example.com
      mission: To provide support and resources to the community.
      yearFounded: "2024"
      socials:
        website: https://www.example.com
        facebook: https://www.facebook.com/example
        twitterOrX: https://x.com/example
        instagram: https://www.instagram.com/example
        linkedin: https://www.linkedin.com/company/example
        otherSocials:
          youtube: https://www.youtube.com/example
    pointOfContact:
      name:
        prefix: Dr.
        firstName: Jane
        middleName: Edward
        lastName: Doe
        suffix: Jr.
      title: Chief Executive Officer
      addresses:
        primary:
          street1: 123 Main St
          city: Anytown
          stateOrProvince: CA
          country: US
          postalCode: "12345"
        otherAddresses:
          work:
            street1: 123 Main St
            city: Anytown
            stateOrProvince: CA
            country: US
            postalCode: "12345"
          home:
            street1: 123 Main St
            city: Anytown
            stateOrProvince: CA
            country: US
            postalCode: "12345"
      phones:
        primary:
          countryCode: "+1"
          number: 444-456-1230
          isMobile: true
        otherPhones:
          home:
            countryCode: "+1"
            number: 333-456-1230
            isMobile: false
      emails:
        primary: john.doe@example.com
        otherEmails:
          work: john.doe@work.com
          personal: john.doe@gmail.com
          school: john.doe@school.edu
    proposal:
      title: Example Project
      description: Example project to serve community needs.
      amountRequested:
        amount: "100000"
        currency: USD
      periodStartDate: 2024-01-01
      periodEndDate: 2024-12-31
    opportunity:
      id: 083b4567-e89d-42c8-a439-6c1234567890
      title: Example Opportunity
description: The base model for an application.
$defs:
  RecordCustomField:
    type: object
    properties: {}
    unevaluatedProperties:
      $ref: CustomField.yaml
