export const styles = {
  formGroup: {
    flex: 1,
    display: "flex",
    flexDirection: "column" as const,
    gap: "1rem",
  },
  formSection: {
    flex: 1,
    padding: "1rem",
    borderRadius: "0.5rem",
    background: "var(--sl-color-gray-7)",
    color: "var(--sl-color-white)",
  },
  formHeader: {
    marginBottom: "1rem",
    fontSize: "1.2rem",
    fontWeight: 600,
    color: "var(--sl-color-white)",
  },
  row: {
    display: "flex",
    gap: "1rem",
  },
  selectLabel: {
    fontWeight: 600,
    marginBottom: 4,
    display: "block",
    color: "var(--sl-color-white)",
  },
  select: {
    padding: "0.5rem",
    borderRadius: 6,
    border: "1px solid var(--sl-color-gray-4)",
    fontSize: 16,
    width: "100%",
    background: "var(--sl-color-gray-7)",
    color: "var(--sl-color-white)",
  },
  button: {
    padding: "0.75rem 1.5rem",
    minWidth: "8rem",
    borderRadius: "8rem",
    border: "none",
    background: "var(--sl-color-text-accent)",
    color: "var(--sl-color-black)",
    fontSize: 16,
    cursor: "pointer",
    alignSelf: "flex-start",
  },
  code: {
    background: "var(--sl-color-gray-6)",
    borderRadius: 6,
    padding: "1rem",
    fontFamily: "monospace",
    fontSize: 14,
    whiteSpace: "pre-wrap" as const,
    wordBreak: "break-all" as const,
    color: "var(--sl-color-white)",
  },
};
