name: Internal - Task
description: Describe a task that needs to be completed
type: Task
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and concise summary of the task
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance criteria
      description: What conditions must be satisfied to consider this task done?
    validations:
      required: true
