emit:
  - "@typespec/json-schema"
  - "@typespec/openapi3"
  - "typespec-versioning-changelog"
options:
  "@typespec/openapi3":
    "omit-unreachable-types": false
  "@typespec/json-schema":
    "seal-object-schemas": true
