name: CD - Publish common-grants-sdk

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag of the release to publish'
        required: true
        type: string

permissions:
  contents: read
  id-token: write

defaults:
  run:
    working-directory: ./lib/python-sdk

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi-publish

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag_name }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v8

      - name: Install dependencies
        run: poetry install

      - name: Run linting
        run: poetry run ruff check .

      - name: Run type checking
        run: poetry run mypy .

      - name: Run tests
        run: poetry run pytest

      - name: Build and publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry build
          poetry publish --dry-run

      - name: Notify completion
        run: |
          echo "Python package published to PyPI"
          echo "Tag: ${{ github.event.inputs.tag_name }}"
