name: CD - Publish @common-grants/core

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag of the release to publish'
        required: true
        type: string

permissions:
  contents: read
  id-token: write

defaults:
  run:
    working-directory: ./lib/core

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm-publish

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag_name }}

      - name: Install dependencies
        run: npm ci

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Run checks
        run: npm run checks

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public --dry-run

      - name: Notify completion
        run: |
          echo "Core package published to npm"
          echo "Tag: ${{ github.event.inputs.tag_name }}"
