name: "CI - CLI: Run Checks"

on:
  workflow_call:
  pull_request:
    paths:
      - lib/cli/**
      - .github/workflows/ci-cli.yml

defaults:
  run:
    working-directory: ./lib/cli

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        # Installs dependencies directly from package.lock
        # and skips dependency resolution etc.
        run: npm ci

      - name: Lint and format
        run: |
          npm run check:lint
          npm run check:format

      - name: Run tests
        run: npm run test

      - name: Build library
        run: npm run build

      - name: Audit dependencies
        run: npm audit
