name: CI - Publish @common-grants/core (dry run)

on:
  pull_request:
    branches:
      - main
    paths:
      - "specs/**" # Trigger only if files in the `specs/` directory are changed

defaults:
  run:
    working-directory: ./specs

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Dry run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --dry-run
