name: "CI - Template: FastAPI Run Checks"

on:
  workflow_call:
  pull_request:
    paths:
      - templates/fast-api/**
      - .github/workflows/ci-template-fast-api.yml

defaults:
  run:
    working-directory: ./templates/fast-api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v8

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install CommonGrants CLI
        run: npm install -g @common-grants/cli

      - name: Install package
        run: make install

      - name: Run linting, formatting, and type checking
        run: make checks

      - name: Run tests
        run: make test-coverage

      - name: Generate and validate OpenAPI spec
        run: make check-spec
